<?php
$plugin = array(
  'title' => t('Master'),
  'category' => t('Custom'),
  'icon' => 'master.png',
  'theme' => 'master',
  'admin theme' => 'master-admin',
  'admin css' => 'master-admin.css',
  'regions' => array(
    'header' => t('Header'),
    'slideshow' => t('Slideshow'),
    'menu' => t('Main Menu'),
    'page_content' => t('Content'),
    'footer_left' => t('Footer Left'),
    'footer_right' => t('Footer Right'),
    'popup_region' => t('Hidden popup Region'),
    'preface_top' => t('Preface top'),
  ),
);
